# File Path: E:/خاص احمد جعفر/برمجة/مشاريع/hr_fastapi/app/services\headers.py
# File Name: headers.py
# -----------------------------------------



EMPLOYEE_hEADERS = {
    "employee_id": "code",
    "code": "code",
    "الكود": "code",
    "كود الموظف": "code",
    "رقم الموظف": "code",
    "legacy_code": "legacy_code",
    "الكود القديم": "legacy_code",
    "full_name": "name",
    "name": "name",
    "الاسم": "name",
    "اسم الموظف": "name",
    "الاسم الكامل": "name",
    "national_id": "national_id",
    "الرقم القومي": "national_id",
    "رقم القومي": "national_id",
    "title": "job_title",
    "job_title": "job_title",
    "الوظيفة": "job_title",
    "وظيفة": "job_title",
    "hire_date": "hire_date",
    "تاريخ التعيين": "hire_date",
    "تاريخ التوظيف": "hire_date",
    "company_name": "company_name",
    "company": "company_name",
    "company_na": "company_name",
    "company_name_ar": "company_name",
    "tenant_name": "company_name",
    "اسم_الشركة": "company_name",
    "اسم الشركة": "company_name",
    "site_name": "site_name",
    "site": "site_name",
    "اسم الموقع": "site_name",
    "cost_center": "cost_center",
    "cost_center_name": "cost_center",
    "مركز_التكلفة": "cost_center",
    "مركز التكلفة": "cost_center",
    "department": "department",
    "department_name": "department",
    "القسم": "department",
    "الإدارة": "department",
    "employee_category": "employee_category",
    "employee_e_catego": "employee_category",
    "الادارة / المشروع": "department",
    "department_id": "department",
    "insured": "insurance_status",
    "is_insured": "insurance_status",
    "التأمين": "insurance_status",
    "insurance": "insurance_status",
    "insurance_status": "insurance_status",
    "مؤمن": "insurance_status",
    "not_insured": "insurance_status",
    "work_status": "work_status",
    "workstatus": "work_status",
    "work status": "work_status",
    "حالة_العمل": "work_status",
    "حالة_العمل": "work_status",
    "حالة العمل": "work_status",
    "مبيت": "overnight"
}

SALARY_hEADERS = {
    "name": "name",
    "full_name": "name",
    "الاسم": "name",
    "salary_date": "salary_date",
    "تاريخ المرتب": "salary_date",
    "date": "salary_date",
    "التاريخ": "salary_date",
    "month": "month",
    "شهر": "month",
    "year": "year",
    "salary_year": "year",
    "base_salary": "base_salary",
    "الراتب الاساسي الاجمالي": "base_salary",
    "اساسي": "base_salary",
    "net_salary": "net_salary",
    "صافي الراتب المستحق": "net_salary",
    "الصافي": "net_salary",
    "insurance_number": "insurance_number",
    "الرقم التامينين": "insurance_number",
    "national_id": "national_id",
    "الرقم القومي": "national_id",
    "legacy_code": "legacy_code",
    "الكود القديم": "legacy_code"
}

ATTENDANCE_hEADERS = {
    "name": "name",
    "full_name": "name",
    "الاسم": "name",
    "date": "date",
    "التاريخ": "date",
    "status": "status",
    "الحالة": "status",
    "shift": "shift",
    "وردية": "shift",
    "national_id": "national_id",
    "الرقم القومي": "national_id",
    "legacy_code": "legacy_code",
    "الكود القديم": "legacy_code"
}