# app/services/headers.py

EMPLOYEE_HEADERS = {
    "full name": "full_name",
    "الاسم": "full_name",
    "اسم الموظف": "full_name",
    "national id": "national_id",
    "الرقم القومي": "national_id",
    "legacy code": "legacy_code",
    "كود قديم": "legacy_code",
    "hire date": "hire_date",
    "تاريخ التعيين": "hire_date",
    "insured": "insured",
    "مؤمن": "insured",
    "overnight": "overnight",
    "مبيت": "overnight",
    "site": "site_name",
    "الموقع": "site_name",
    "company": "company_name",
    "الشركة": "company_name",
    "cost center": "cost_center",
    "مركز التكلفة": "cost_center",
    "phone": "phone",
    "status": "status",
    "title": "title",
    "site id": "site_id",
}

SALARY_HEADERS = {
    "الكود القديم": "legacy_code",
    "كود الموظف": "legacy_code",
    "الاسم": "name",
    "موقع العمل": "site",
    "الادارة / المشروع": "cost_center",
    "الوظيفة": "role",
    "تاريخ التأمين": "hire_date",
    "اساسي": "base_salary",
    "الأساسي": "base_salary",
    "اعاشة": "allowances_food",
    "سفر": "allowances_travel",
    "مواصلات": "allowances_transport",
    "بدلات اخري": "allowances_other",
    "تأمين اجتماعي (العامل)": "ded_insurance_employee",
    "أقساط": "ded_loans",
    "صافي الراتب المستحق": "net_salary",
    "الصافي": "net_salary",
    "مرتبات شهر": "salary_date",
    "تاريخ": "salary_date",
    "عدد أيام الحضور": "attendance_days",
    "عدد ايام الغياب": "absence_days",
    "الرقم القومي": "national_id",
    "الرقم التأميني": "insurance_number",
}
