"""
Level 3 multi-key relations
"""

from .employee_asset_project_site import EmployeeAssetProjectSite
from .employee_asset_site_role import EmployeeAssetSiteRole
from .employee_project_role_cost_center import EmployeeProjectRoleCostCenter
from .employee_project_site_cost_center import EmployeeProjectSiteCostCenter
from .employee_project_site_department import EmployeeProjectSiteDepartment
from .employee_training_certification_project import EmployeeTrainingCertificationProject
from .employee_training_project_site import EmployeeTrainingProjectSite
from .tenant_site_department_cost_center import TenantSiteDepartmentCostCenter
